-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: 04-Ago-2022 às 15:00
-- Versão do servidor: 5.7.24
-- versão do PHP: 7.2.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbetec`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `cursos`
--

DROP TABLE IF EXISTS `cursos`;
CREATE TABLE IF NOT EXISTS `cursos` (
  `cod_curso` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(110) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo` varchar(70) COLLATE utf8mb4_unicode_ci NOT NULL,
  `duracao` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `coordenador` varchar(110) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mercado` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `descricao` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `eixo` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `imagem_capa` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `periodo` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`cod_curso`)
) ENGINE=MyISAM AUTO_INCREMENT=223 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Extraindo dados da tabela `cursos`
--

INSERT INTO `cursos` (`cod_curso`, `nome`, `tipo`, `duracao`, `coordenador`, `mercado`, `descricao`, `eixo`, `imagem_capa`, `periodo`) VALUES
(7, 'Ensino Médio Regular', 'Ensino Médio', '6 Semestres', 'Marcelo Aparecido Decurcio', 'Curso destinado à continuidade de estudos em nível superior e/ou técnico de nível médio.', 'O ensino médio destina-se aos candidatos que tenham concluído o ensino fundamental e compõe-se por duas partes: Base Nacional Comum e Parte Diversificada. As disciplinas da Base Nacional Comum, direcionadas para a formação geral do estudante, são as já tradicionalmente estudadas, como Língua Portuguesa e Literatura, Matemática, História, Geografia, Química, Física, Biologia, Educação Física e Artes. As disciplinas da Parte Diversificada objetivam ao desenvolvimento de capacidades e de condutas importantes na atualidade, visando à formação para o exercício da cidadania e preparação para o trabalho. O oferecimento dessas disciplinas é diferenciado nas Etecs, as quais dispõem de autonomia para optar por projetos, pelo ensino de filosofia, de sociologia e/ou espanhol. O inglês, que também integra a Parte Diversificada, é obrigatório no ensino médio.', 'Ensino Médio', 'regular.jpg', 'Matutino'),
(18, 'Novotec em Química', 'Ensino Médio', '6 Semestres', 'Renê Guerreiro de Souza Cintra', 'Indústrias farmacêuticas, químicas e de alimentos, instituições científicas e de pesquisa.', 'Ensino Médio com Habilitação Técnica Profissional de Técnico em Química.\r\nÉ composto por três séries anuais, com aulas em meio período (manhã). A grade curricular mescla disciplinas da base nacional comum ao Ensino Médio com componentes do Ensino Técnico.\r\nAo completar as três séries, o aluno terá concluído o Ensino Médio e obterá o diploma de Técnico, que lhe dará o direito de exercer a habilitação profissional e de prosseguir os estudos no nível da Educação Superior.\r\n\r\n ', 'Ensino Médio', 'novoquimica.jpg', 'Matutino'),
(1, 'Novotec em Desenvolvimento de Sistemas', 'Ensino Médio', '6 Semestres', 'Simone Confortini Correia', 'Empresas e departamentos de desenvolvimento de sistemas em organizações governamentais e não governamentais, podendo também atuar como profissional autônomo.', 'Ensino Médio com Habilitação Técnica Profissional - Desenvolvimento de Sistemas\r\nÉ composto por três séries anuais, com aulas em meio período (manhã). A grade curricular mescla disciplinas da base nacional comum ao Ensino Médio com componentes do Ensino Técnico.\r\nAo completar as três séries, o aluno terá concluído o Ensino Médio e obterá o diploma de Técnico, que lhe dará o direito de exercer a habilitação profissional e de prosseguir os estudos no nível da Educação Superior.', 'Ensino Médio', 'novodes.jpg\r\n', 'Matutino'),
(12, 'Novotec em Recursos Humanos', 'Ensino Médio', '6 Semestres', 'Fernanda Moreira Ferreira', 'Organizações públicas, privadas, mistas e do terceiro setor ou como autônomos e consultores.', 'Ensino Médio com Habilitação Profissional de Técnico em Recursos Humanos.\r\nÉ composto por três séries anuais, com aulas em meio período (manhã). A grade curricular mescla disciplinas da base nacional comum ao Ensino Médio com componentes do Ensino Técnico.\r\nAo completar as três séries, o aluno terá concluído o Ensino Médio e obterá o diploma de Técnico, que lhe dará o direito de exercer a habilitação profissional e de prosseguir os estudos no nível da Educação Superior.\r\n\r\n ', 'Ensino Médio', 'novorh.jpg', 'Matutino'),
(4, 'Novotec em Administração', 'Ensino Médio', '6 Semestres', 'Elaine Uranga Clivelaro Buturi', 'Instituições públicas, privadas e do terceiro setor; profissional autônomo em consultoria e treinamentos.', 'É composto por três séries anuais, com aulas em meio período (manhã). A grade curricular mescla disciplinas da base nacional comum ao Ensino Médio com componentes do Ensino Técnico.\r\nAo completar as três séries, o aluno terá concluído o Ensino Médio e obterá o diploma de Técnico, que lhe dará o direito de exercer a habilitação profissional e de prosseguir os estudos no nível da Educação Superior.', 'Ensino Médio', 'novoadm.jpg', 'Matutino'),
(10, 'Itinerário Formativo em Linguagens', 'Ensino Médio', '6 Semestres', 'Marcelo Aparecido Decurcio', 'Curso destinado à continuidade de estudos em nível superior e/ou técnico de nível médio.', 'As aulas do Ensino Médio com ênfase em Linguagens, Ciências Humanas e Sociais são realizadas em meio período (manhã). As competências da Base Nacional Comum Curricular (BNCC) são organizadas de acordo com as especificidades do curso. Ao optar por essa modalidade, o aluno tem a oportunidade de se aprofundar em linguagem oral e escrita, exercitar capacidades intelectuais e expressivas, aprender a língua materna e idiomas estrangeiros, bem como estudar o homem do ponto de vista social, cultural e histórico. Ao concluir o Ensino Médio com ênfase em Linguagens, Ciências Humanas e Sociais o estudante poderá prosseguir estudos em nível superior preferencialmente nas áreas de: Administração, Arquitetura e Humanismo, Artes, Audiovisual, Ciências da Informação e Comunicação, Ciências Humanas e Sociais, Comércio Exterior, Comunicações, Design, Direito, Economia, Eventos, Filosofia, Fotografia, Geografia, História, Letras, Marketing, Moda, Multimídia, Pedagogia, Produção Cultural, Psicologia, Publicidade, Secretariado, Sociologia, Turismo e Hospitalidade, entre outras.', 'Ensino Médio', 'novoiti.jpg', 'Matutino'),
(3, 'Técnico em Enfermagem', 'Curso Técnico', '4 Semestres', 'Andréa Márcia Pinto Finote', 'Unidades básicas de saúde, hospitais, casa de repouso, escolas e clínicas.', 'O aluno aprende técnicas para auxiliar na recuperação de um paciente, assim como a prevenção de doenças, orientação para exames, entre outros procedimentos. O curso tem base na biologia, para aprender sobre o corpo humano; na matemática, para cálculos de medida para medicações; na física, para entender os riscos que o paciente corre, como a velocidade de uma batida de um veículo para entender os tipos de lesões possíveis, por exemplo; e português, para escrever corretamente no prontuário do paciente. \r\nAtuação: o técnico cumpre função assistencial ao enfermeiro, como cuidados básicos em pacientes graves, aplicação de vacina, dar um banho em um paciente, auxiliar em exames, entre outras funções. Pode atuar na área administrativa, na prevenção e pode montar ações educativas, na área de segurança do trabalho. ', 'Ambiente e Saúde', 'enfermagem.jpg', 'Noturno'),
(14, 'Técnico em Meio Ambiente', 'Curso Técnico', '3 Semestres', 'Éverton Henrique Gonçales Cardoso', 'Instituições públicas, terceiro setor, empresas prestadoras de serviços na área ambiental, laboratórios e centros de pesquisa, indústrias, consultorias técnico-ambientais.', 'O Técnico em Meio Ambiente é o profissional que coleta, armazena e interpreta informações, dados e documentações ambientais. Colabora na elaboração de laudos, relatórios e estudos ambientais. Auxilia na elaboração, no acompanhamento e na execução de sistemas de gestão ambiental. Atua na organização de programas de educação ambiental, de conservação e de preservação de recursos naturais, de redução, reúso e reciclagem. Identifica as intervenções ambientais, analisa suas consequências e operacionaliza a execução de ações para preservação, conservação, otimização, minimização e remediação dos seus efeitos.', 'Ambiente e Saúde', 'meioambiente.jpg', 'Noturno'),
(13, 'Técnico em Farmácia', 'Curso Técnico', '3 Semestres', 'Renê Guerreiro de Souza Cintra', 'Drogarias, indústrias farmacêuticas, postos de medicação, hospitais, farmácia de manipulação, distribuidoras de medicamentos.', 'Manipula medicamentos, realiza testes de controle de qualidade, auxilia nas rotinas das farmácias, no armazenamento dos medicamentos e no controle do estoque. Orienta os pacientes sobre receitas medicas, conservação e uso correto de cada medicamento.', 'Ambiente e Saúde', 'farmacia.jpg', 'Noturno e Diurno'),
(11, 'Técnico em Recursos Humanos', 'Curso Técnico', '3 Semestres', 'Rodrigo Fernandes', 'Organizações públicas, privadas, mistas e do terceiro setor ou como autônomos e consultores.', 'Profissional que detém aptidão para intermediar as relações interpessoais e éticas de uma organização. É habilitado para trabalhar na execução das rotinas administrativas de pessoal com base na Legislação Trabalhista e Previdenciária. Auxilia no controle e avaliação de subsistemas de gerenciamento e contribui para a implementação das estratégias organizacionais. Compromete-se com o desenvolvimento humano, administra pessoal, promove ações de treinamento, identifica e sugere plano de benefícios. Descreve e classifica postos de trabalho, aplica questionários e processa informações acerca dos trabalhadores. Atua nos processos de recrutamento, seleção e integração, assessora as relações de trabalho e sistemas de avaliação de desempenho. Presta serviços de comunicação oral e escrita, liderança, motivação, formação de equipes e desenvolvimento de pessoal com empenho no crescimento simultâneo, individual e do grupo. Realiza ações empreendedoras e em processos de orientação sobre a importância da segurança no trabalho e da saúde ocupacional. Propõe relações positivas propícias para o clima organizacional e responsabilidade social aos diversos públicos.', 'Gestão e Negócios', 'rhnoite.jpg', 'Noturno'),
(8, 'Técnico em Contabilidade', 'Curso Técnico', '3 Semestres', 'Éder Aparecido de Sousa', 'No setor de Contabilidade de qualquer tipo de empresa e em escritórios de Contabilidade.', 'Ajuda na preparação dos documentos necessários para a abertura ou o encerramento de uma empresa. Calcula os tributos (impostos, taxas e contribuições) que uma empresa deve pagar ao governo. Emite notas fiscais, gera boletos bancários e guias para o pagamento dos tributos. Registra os bens comprados e vendidos pela empresa. Elabora planilhas de controle de bens ou de estoque de mercadorias e produtos. Organiza e arquiva documentos. Auxilia na produção de relatórios diversos referentes às contas da empresa, ao cálculo do lucro ou prejuízo, do desempenho de vendas, das dívidas e dos demais demonstrativos de resultados.', 'Gestão e Negócios', 'contabilidade.jpg', 'Noturno'),
(9, 'Técnico em Marketing', 'Curso Técnico', '3 Semestres', 'Fernanda Moreira Ferreira', 'Instituições públicas, privadas e do terceiro setor. Área Comércio. Empresas de consultoria e de forma autônoma.', 'É o profissional que colabora na elaboração do plano de marketing da empresa e no planejamento e implementação de ações de marketing pontuais. Executa tarefa de análise das vendas, preços e produtos. Operacionaliza as políticas de comunicação da empresa: fidelização de clientes, relação com fornecedores ou outras entidades. Executa o controle, estatísticas e operações de telemarketing. Operacionaliza políticas de apresentação dos produtos no ponto de venda. Participa na elaboração e na realização de estudos de mercado e interpreta e aplica a legislação da área.', 'Gestão e Negócios', 'marketing.jpg', 'Noturno'),
(2, 'Técnico em Logística', 'Curso Técnico', '3 Semestres', 'Éder Aparecido de Sousa', 'Instituições públicas, privadas e do terceiro setor.', 'Executa e colabora na gestão dos processos de planejamento, operação e controle: de programação da produção de bens e serviços, programação de manutenção de máquinas e de equipamentos, de compras, de recebimento, de armazenamento, de estoques, de movimentação, de expedição, transporte e distribuição de materiais e produtos, utilizando tecnologia de informação. Presta atendimento aos clientes. Implementa os procedimentos de controle de custos, qualidade, segurança e higiene do trabalho no sistema logístico.', 'Gestão e Negócios', 'logistica.jpg', 'Noturno'),
(15, 'Técnico em Administração', 'Curso Técnico', '3 Semestres', 'Éder Aparecido de Sousa', 'Empresas privadas, seja de comércio, serviço ou indústria, órgãos públicos (prefeituras, secretarias de governo, ministérios do governo federal etc.) e ONGs.', 'Trabalha em vários departamentos. No setor de compras, por exemplo, pode elaborar pedidos de compra de produtos, cadastrar fornecedores assim como conferir a entrega das mercadorias adquiridas. Na área de produção, pode fazer planilhas de controle de processos e produtos, registrando quais já foram produzidos e em qual quantidade. No departamento de vendas, também pode elaborar planilhas para acompanhar o desempenho das vendas, cadastrar clientes, preencher notas fiscais e gerar boletos bancários. No setor de Recursos Humanos, o técnico pode trabalhar calculando salários e benefícios dos funcionários e auxiliando nos processos de contratação e demissão de pessoal. Em qualquer área, pode atender clientes e fornecedores e redigir documentos, como e-mails, memorandos e atas. ', 'Gestão e Negócios', 'admnoite.jpg', 'Noturno'),
(17, 'Técnico em Informática para Internet', 'Curso Técnico', '3 Semestres', 'Daiane Marcela Piccolo', 'Empresas de desenvolvimento de sites ou de sistemas e empresas de marketing digital. O técnico também pode trabalhar por conta própria, como freelancer, prestando serviço a outras empresas.', 'O processo de criação de sites e o de desenvolvimento de programas que podem ser utilizados em páginas na internet. Para programar, o aluno vai estudar raciocínio lógico e linguagens de programação, que utiliza comandos para desenvolver funcionalidades e dar forma a um site. Além disso, o estudante aprenderá um pouco de design com o objetivo de tornar a página mais agradável e fácil de ser utilizada. O aluno aprenderá ainda como criar e alterar bancos de dados que vão alimentar os sites. Noções de marketing digital para a web e de empreendedorismo também serão ensinadas ao longo do curso.\r\nCria websites de acordo com as necessidades do cliente, identificando e sugerindo as melhores soluções; faz a manutenção de portais, sites e intranets; cuida da identidade visual das páginas de uma empresa; faz a customização de plataformas de conteúdo para web, como blogs e sites de comércio eletrônico; cria e realiza manutenção de bancos de dados para websites; adapta as páginas para abrigar vídeos, áudios e funções que facilitem a acessibilidade, como comandos de voz, por exemplo; trata e otimiza imagens para uso na internet; e prepara o layout de mensagens que são enviadas por e-mail (newsletter ou e-mail marketing), entre outras atividades.', 'Informação e Comunicação', 'infparainternet.jpg', 'Noturno'),
(20, 'Técnico em Redes de Computadores', 'Curso Técnico', '3 Semestres', 'Ricardo Fassina Maioli', 'Em qualquer empresa que necessite de instalação e manutenção de redes de computadores, especialmente as empresas de telecomunicações e telemarketing, além de órgãos públicos.', 'Conectar computadores em rede, de modo que as máquinas compartilhem recursos como arquivos, internet, contas de e-mail e impressoras. O estudante vai conhecer os sistemas operacionais utilizados pelas redes e seus padrões de comunicação e as configurações de segurança da informação. Aprenderá como controlar o tráfego de dados, fazer cópias de segurança, programar a automação de tarefas e montar o cabeamento estruturado, que conecta os computadores aos servidores e armários de telecomunicações. Conhecimentos de matemática e física serão revisados ao longo do curso para o aprendizado de cálculo com números binários, eletrônica, propagação de ondas eletromagnéticas e óticas.\r\nInstala e configura computadores e equipamentos de informática em rede. É responsável também por administrar, manter e analisar redes de computadores. O técnico instala ainda sistemas operacionais para os servidores que gerenciam as redes e configura o compartilhamento de recursos e as permissões de segurança entre as máquinas e os usuários. Além disso, o profissional monta os cabos e os armários de telecomunicações que abrigam servidores e outros equipamentos para rede; cuida da documentação, listando os dispositivos utilizados e executa projetos de implantação de redes de computadores em empresas.', 'Informação e Comunicação', 'redes.jpg', 'Noturno'),
(19, 'Técnico em Desenvolvimento de Sistemas', 'Curso Técnico', '3 Semestres', 'Daiane Marcela Piccolo', 'Empresas e departamentos de desenvolvimento de sistemas em organizações governamentais e não governamentais, podendo também atuar como profissional autônomo.', 'Analisa e projeta sistemas. Constrói, documenta, realiza testes e mantém sistemas de informação. Utiliza ambientes de desenvolvimento e linguagens de programação específica. Modela, implementa e mantém bancos de dados.', 'Informação e Comunicação', 'dsnoite.jpg', 'Noturno'),
(6, 'Técnico em Informática', 'Curso Técnico', '3 Semestres', 'Simone Confortini Correia', 'Instituições públicas, privadas e do terceiro setor que demandem sistemas computacionais, especialmente envolvendo programação de computadores.', 'Desenvolve e opera sistemas, aplicações e interfaces gráficas. Monta estruturas de banco de dados e codifica programas. Projeta, implanta e realiza manutenção de sistemas e aplicações. Seleciona recursos de trabalho, linguagens de programação, ferramentas e metodologias para o desenvolvimento de sistemas.', 'Informação e Comunicação', 'informatica.jpg', 'Noturno'),
(16, 'Técnico em Química', 'Curso Técnico', '3 Semestres', 'Renê Guerreiro de Souza Cintra', 'Indústria química, setor alimentício, área agrícola, vendas e assistência técnica.', 'A matemática é utilizada para a base de cálculos. A físico-química também é uma disciplina importante no curso. O aluno aprenderá a manipular instrumentos como microscópio, balança analítica e outros equipamentos voltados a análises químicas. Outro ponto importante é o entendimento sobre a tecnologia de processos industriais, onde os alunos aprendem a transformação química e a evolução da matéria-prima até o produto final.', 'Produção Industrial', 'quimicanoite.jpg', 'Noturno'),
(5, 'Técnico em Açúcar e Álcool', 'Curso Técnico', '3 Semestres', 'Adriana Ferreira Barbosa', 'Usina de açúcar e álcool, área agrícola, indústrias direcionadas ao processo de produção de cachaça ou açúcar mascavo, todas as empresas da área química, vendas e assistência técnica.', 'Realiza a análise de matéria-prima na extração do caldo de cana e na centrifugação do açúcar. O profissional realiza o controle de qualidade. Pode atuar na área de cultivo da matéria-prima e com a tecnologia de subprodutos que sobram da produção do açúcar e do álcool.', 'Produção Industrial', 'acucarealcool.jpg', 'Noturno'),
(21, 'Técnico em Segurança do Trabalho', 'Curso Técnico', '3 Semestres', 'Andréa Márcia Pinto Finote', 'Empresas públicas e privadas, como indústrias, hospitais, empresas comerciais, mineradoras, de construção civil e área rural.', 'Profissional que elabora e implementa políticas de saúde e de segurança do trabalho (SST). Realiza auditorias, acompanhamento e avaliação na área. Identifica variáveis de controle de doenças, de qualidade e do meio ambiente. Desenvolve ações educativas na área de saúde e segurança do trabalho. Participa de perícias e fiscalizações e atua em processos de negociação. Participa da adoção de tecnologias e de processos de trabalho. Gerencia documentação de SST. Investiga, analisa acidentes e recomenda medidas para sua prevenção e controle.', 'Segurança', 'seguranca.jpg', 'Noturno');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
